repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: >
          sudo docker run --rm
          -v /home/ren/projects/SupChainSec/hmk1:/workspace
          trufflesecurity/trufflehog:latest
          filesystem /workspace
        language: system
        stages: ["pre-commit", "pre-push"]
        # tutorial at https://dev.to/rafaelherik/using-trufflehog-and-pre-commit-hook-to-prevent-secret-exposure-edo