[tool.poetry]
name = "hmk1"
version = "0.1.0"
description = "A package that is quite pointless"
authors = ["some dude <jr5887@nyu.edu>"]
maintainers = [
    "John Smith <johnsmith@example.org>",
    "Jane Smith <janesmith@example.org>",
]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
mypy = "1.13.0"
autodocstrings = "0.1.3"
annotated-types = "0.7.0"
anyio = "4.6.2.post1"
astor = "0.8.1"
attrs = "24.2.0"
black = "24.10.0"
certifi = "2024.8.30"
cffi = "1.17.1"
cfgv = "3.4.0"
charset-normalizer = "3.3.2"
click = "8.1.7"
coverage = "7.6.4"
cryptography = "43.0.1"
distlib = "0.3.9"
distro = "1.9.0"
exceptiongroup = "1.2.2"
filelock = "3.16.1"
git-filter-repo = "2.45.0"
gitdb = "4.0.11"
gitdb2 = "4.0.2"
gitpython = "3.0.6"
h11 = "0.14.0"
httpcore = "1.0.6"
httpx = "0.27.2"
identify = "2.6.2"
idna = "3.10"
iniconfig = "2.0.0"
jiter = "0.7.0"
jsonschema = "4.23.0"
jsonschema-specifications = "2024.10.1"
markdown-it-py = "3.0.0"
mdurl = "0.1.2"
mypy-extensions = "1.0.0"
nodeenv = "1.9.1"
openai = "1.54.3"
packaging = "24.2"
pathspec = "0.12.1"
platformdirs = "4.3.6"
pluggy = "1.5.0"
pre-commit = "4.0.1"
pycparser = "2.22"
pydantic = "2.9.2"
pydantic-core = "2.23.4"
pygments = "2.18.0"
pytest = "8.3.3"
pytest-cov = "6.0.0"
pytest-mock = "3.14.0"
pyyaml = "6.0.2"
referencing = "0.35.1"
requests = "2.32.3"
rich = "13.9.4"
rpds-py = "0.21.0"
scapy = "2.6.0"
shellingham = "1.5.4"
smmap = "5.0.1"
sniffio = "1.3.1"
tomli = "2.0.2"
tqdm = "4.67.0"
trufflehogregexes = "0.0.7"
typer = "0.13.0"
typing-extensions = "4.12.2"
urllib3 = "2.2.3"
virtualenv = "20.27.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
